---
title: "Sahil_A9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
```{r}
ca_zips <- zctas("CA")
bay_county_names <- c("Alameda", "Contra Costa", "Napa", "San Francisco", "San Mateo", "Santa Clara", "Solano", "Sonoma")
bay_counties <- counties("CA") %>% filter(NAME %in% bay_county_names)


bay_zips <- ca_zips[bay_counties,]
bay_zips <-
  ca_zips %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_zips %>% select(GEOID10)) %>% 
  st_as_sf()
saveRDS(bay_zips, "bay_zips.rds")

```

```



```{r}
library(tidyverse)
library(censusapi)
library(sf)
library(mapview)
library(tigris)
library(leaflet)
library(tidyr)
library(dplyr)
library(ggplot2)
library(flexdashboard)
```

```{r}
pge_data_raw <- readRDS("pge_data_raw.rds")

bay_zips <- readRDS("bay_zips.rds")

pge_data <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Commercial",
      "Elec- Residential"
    )
  ) %>% 
  group_by(
    MONTH, 
    YEAR, 
    CUSTOMERCLASS
  ) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )
```

